export { default as Home } from './Home'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Wishlist } from './Wishlist'
export { default as Cate } from './Cate'
export { default as Cart } from './Cart'
export { default as Shop } from './Shop'
export { default as Checkout } from './Checkout'
export { default as ProductDetail } from './ProductDetail'
export { default as Blog } from './Blog'
export { default as BlogList } from './Blog/BlogList'
export { default as BlogDetail } from './Blog/BlogDetail'
export { default as Account } from './Account'
export { default as Auth } from './Auth'
export { default as CateDetail } from './CateDetail'


